-- Database: Tester

-- DROP DATABASE IF EXISTS "Tester";

CREATE DATABASE "Tester"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_Finland.1252'
    LC_CTYPE = 'English_Finland.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	-- Database: Tester

-- DROP DATABASE IF EXISTS "Tester";

CREATE DATABASE "Tester"
    WITH
    OWNER = postgres
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_Finland.1252'
    LC_CTYPE = 'English_Finland.1252'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;
	
	-- CREATE THE DIRECTORS TABLE
	
	CREATE TABLE DIRECTORS(
		DIRECTOR_ID SERIAL PRIMARY KEY,
		FIRST_NAME VARCHAR(30),
		LAST_NAME VARCHAR(30) NOT NULL,
		DATE_OF_BIRTH DATE,
		NATIONALITY VARCHAR(20)
	);
	
	-- CREATE ACTORS TABLE
	
	CREATE TABLE ACTORS(
		ACTOR_ID SERIAL PRIMARY KEY,
		FIRST_NAME VARCHAR(30),
		LAST_NAME VARCHAR(30),
		GENDER CHAR(1),
		DATE_OF_BIRTH DATE
	);
	
	--CREATE THE MOVIES TABLE(WITH FOREIGN KEY)
	
	CREATE TABLE MOVIES (
		MOVIE_ID SERIAL PRIMARY KEY,
		MOVIE_NAME VARCHAR(50) NOT NULL,
		MOVIE_LENGTH INT,
		MOVIE_LANG VARCHAR(20),
		RELEASE_DATE DATE,
		AGE_CERTIFICATE VARCHAR(5),
		DIRECTOR_ID INT REFERENCES DIRECTORS (DIRECTOR_ID)
	);
	
	CREATE TABLE MOVIE_REVENUES(
		REVENUE_ID SERIAL PRIMARY KEY,
		MOVIE_ID INT REFERENCES MOVIES (MOVIE_ID),
		DOMESTIC_TAKINGS NUMERIC(6,2),
		INTERNATIONAL_TAKINGS NUMERIC(6,2)
	);
	
	--CREATE THE MOVIES_ACTORS TABLE
	
	CREATE TABLE MOVIES_ACTORS(
		MOVIE_ID INT REFERENCES MOVIES (MOVIE_ID),
		ACTOR_ID INT REFERENCES ACTORS (ACTOR_ID),
		PRIMARY KEY (MOVIE_ID, ACTOR_ID)
	);
	
	SELECT * FROM MOVIES_ACTORS;
	
	SELECT * FROM MOVIES;
	
	ALTER TABLE MOVIES
	ADD COLUMN COUNTRY VARCHAR(20);
	
	ALTER TABLE MOVIES
	DROP COLUMN COUNTRY;
	
	ALTER TABLE MOVIES
	ALTER COLUMN MOVIE_LANG TYPE VARCHAR(25);
	
	
	